server:
 port: 8080

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/mydb
  username: myuser
  password: mypassword

 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

 mail:
  host: smtp.gmail.com
  port: 587
  username: e.selimbark@gmail.com
  password: ziasvmkxnmsodgkt # Gmail App Password
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
      required: true
     ssl:
      enable: false
      trust: smtp.gmail.com
     connectiontimeout: 30000
     timeout: 30000
     writetimeout: 30000
   debug: true

logging:
 level:
  root: INFO
  org.springframework.mail: DEBUG
  com.sun.mail: DEBUG
java:
 net:
  preferIPv4Stack: true

management:
 health:
  mail:
   enabled: false
