server:
 port: 8080

spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/mydb
  username: myuser
  password: mypassword

 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

 mail:
  host: smtp.gmail.com
  port: 587
  username: e.selimbark@gmail.com
  password: jholicxymfaiabcg
  properties:
   mail:
    smtp:
     auth: true
     starttls:
      enable: true
      required: true
     ssl:
      enable: false
      trust: smtp.gmail.com
     connectiontimeout: 10000
     timeout: 10000
     writetimeout: 10000
logging:
 level:
   org:
    springframework.mail: DEBUG
    eclipse.angus.mail: DEBUG



